from sqlalchemy import Column, Integer, String, DECIMAL, CHAR, DateTime, func
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class SetSku(Base):
    __tablename__ = "SET_SKU"

    sku_no = Column(Integer, primary_key=True, autoincrement=True, comment="자동증가 ID")
    company_no = Column(Integer, comment="회사 No")
    sku_id = Column(String(50), unique=True, index=True, nullable=False, comment="SKU ID")
    exposure_id = Column(String(50), comment="노출 ID")
    bundle = Column(String(10), comment="묶음")
    sku_name = Column(String(500), comment="상품명")
    link = Column(String(1000), comment="링크")
    option_type = Column(String(10), default="MANUAL", comment="옵션 사용 타입, 자동 : AUTO, 수동 : MANUAL")
    option_value = Column(String(200), comment="옵션")
    linked_option = Column(String(200), comment="연동옵션")
    linked_spec_id = Column(String(100), comment="연동 Spec Id")
    linked_sku_id = Column(String(100), comment="연동 sku id")
    linked_open_uid = Column(String(100), comment="연동 open uid")
    barcode = Column(String(100), comment="바코드")
    multiple_value = Column(Integer, default=1, comment="판매 구성 수량")
    package_unit_quantity = Column(String(200), comment="포장 개수(단위별 포장 개수)")
    cn_name = Column(String(500), comment="중문명")
    package_vinyl_spec_cd = Column(String(6), comment="포장비닐 규격")
    en_name = Column(String(500), comment="영문명")
    hs_code = Column(String(20), comment="HS코드번호")
    en_name_for_cn = Column(String(500), comment="영문명(중국용)")
    hs_code_cn = Column(String(20), comment="HS코드번호(중국용)")
    fta_cd = Column(String(10), comment="FTA(PROGRESS, NOT_PROGRESS")
    material = Column(String(100), comment="재질")
    length_mm = Column(DECIMAL(10, 2), comment="길이(mm)")
    width_mm = Column(DECIMAL(10, 2), comment="넓이(mm)")
    height_mm = Column(DECIMAL(10, 2), comment="높이(mm)")
    weight_g = Column(DECIMAL(10, 2), comment="중량(g)")
    delivery_status_cd = Column(String(20), comment="납품여부(POSSIBLE, IMPOSSIBLE)")
    sale_price = Column(DECIMAL(15, 2), comment="판매가격")
    cost_yuan = Column(DECIMAL(15, 2), comment="원가-위안화")
    cost_krw = Column(DECIMAL(15, 2), comment="원가-원화")
    supply_price = Column(DECIMAL(15, 2), comment="공급가")
    margin = Column(DECIMAL(5, 2), comment="마진(%)")
    image_path = Column(String(100), comment="SKU 이미지 경로")
    del_yn = Column(Integer, default=0, comment="삭제여부 (1/0)")
    created_at = Column(DateTime(timezone=True), server_default=func.now(), comment="생성일시")
    updated_at = Column(DateTime(timezone=True), onupdate=func.now(), comment="수정일시")
    created_by = Column(Integer, comment="생성자")
    updated_by = Column(Integer, comment="수정자")

class SetCenter(Base):
    __tablename__ = "SET_CENTER"

    center_no = Column(Integer, primary_key=True, autoincrement=True, comment='센터 고유 번호')
    center_initial = Column(String(20), nullable=False, comment='센터 이니셜 (약어)')
    center_name = Column(String(100), nullable=False, comment='센터 이름')
    center_tel = Column(String(20), nullable=True, comment='센터 전화번호')
    center_address = Column(String(255), nullable=True, comment='센터 기본 주소')
    center_address_detail = Column(String(255), nullable=True, comment='센터 상세 주소')
    center_zip = Column(String(10), nullable=True, comment='센터 우편번호')
    del_yn = Column(Integer, default=0, comment="삭제여부 (1/0)")
    created_by = Column(String(50), nullable=True, comment='생성자 ID 또는 이름')
    created_at = Column(DateTime, default=func.now(), comment='생성 일시')
    updated_by = Column(String(50), nullable=True, comment='최종 수정자 ID 또는 이름')
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now(), comment='최종 수정 일시')
